## Instacart Market Basket Analysis

## 1. Data Exploration and Preprocessing

### a. Load the Data:
- Load the CSV files into pandas DataFrames.
- Check for missing values and data types.

**Load the CSV files into pandas DataFrames**

In [9]:
import numpy as np
import pandas as pd

df_aisles = pd.read_csv('aisles.csv')
df_departments = pd.read_csv('departments.csv')
df_order_products = pd.read_csv('order_products__prior.csv')
df_orders = pd.read_csv('orders.csv')
df_products = pd.read_csv('products.csv')

**Check for missing values and data types**

In [10]:
# Create a list of DataFrames
dfs = [df_orders, df_products, df_order_products, df_aisles, df_departments]
df_names = ['Orders', 'Products', 'Order Products', 'Aisles', 'Departments']

# Create a dictionary to hold the missing values information
missing_values_dict = {'DataFrame': [], 'Column': [], 'Missing Values': []}

# Check for missing values in each DataFrame
for df, name in zip(dfs, df_names):
    missing_values = df.isnull().sum()
    for column, missing in missing_values.items():
        missing_values_dict['DataFrame'].append(name)
        missing_values_dict['Column'].append(column)
        missing_values_dict['Missing Values'].append(missing)

# Convert the dictionary to a DataFrame
missing_values_df = pd.DataFrame(missing_values_dict)

In [11]:
missing_values_df

         DataFrame                  Column  Missing Values
0           Orders                order_id               0
1           Orders                 user_id               0
2           Orders                eval_set               0
3           Orders            order_number               0
4           Orders               order_dow               0
5           Orders       order_hour_of_day               0
6           Orders  days_since_prior_order          206209
7         Products              product_id               0
8         Products            product_name               0
9         Products                aisle_id               0
10        Products           department_id               0
11  Order Products                order_id               0
12  Order Products              product_id               0
13  Order Products       add_to_cart_order               0
14  Order Products               reordered               0
15          Aisles                aisle_id               0
16          Aisles                   aisle               0
17     Departments           department_id               0
18     Departments              department               0

### b. Data Cleaning:
- Handle missing values.
- Convert data types (e.g., datetime conversion).
- Merge DataFrames as needed (e.g., joining order_products with products).

**Handle missing values.**

In [12]:
df_orders.fillna({'days_since_prior_order': 0}, inplace=True)
print(df_orders.head(50))
df_orders.dtypes

    order_id  user_id eval_set  order_number  order_dow  order_hour_of_day  \
0    2539329        1    prior             1          2                  8
1    2398795        1    prior             2          3                  7
2     473747        1    prior             3          3                 12
3    2254736        1    prior             4          4                  7
4     431534        1    prior             5          4                 15
5    3367565        1    prior             6          2                  7
6     550135        1    prior             7          1                  9
7    3108588        1    prior             8          1                 14
8    2295261        1    prior             9          1                 16
9    2550362        1    prior            10          4                  8
10   1187899        1    train            11          4                  8
11   2168274        2    prior             1          2                 11
12   1501582        2    prior             2          5                 10
13   1901567        2    prior             3          1                 10
14    738281        2    prior             4          2                 10
15   1673511        2    prior             5          3                 11
16   1199898        2    prior             6          2                  9
17   3194192        2    prior             7          2                 12
18    788338        2    prior             8          1                 15
19   1718559        2    prior             9          2                  9
20   1447487        2    prior            10          1                 11
21   1402090        2    prior            11          1                 10
22   3186735        2    prior            12          1                  9
23   3268552        2    prior            13          4                 11
24    839880        2    prior            14          3                 10
25   1492625        2    train            15          1                 11
26   1374495        3    prior             1          1                 14
27    444309        3    prior             2          3                 19
28   3002854        3    prior             3          3                 16
29   2037211        3    prior             4          2                 18
30   2710558        3    prior             5          0                 17
31   1972919        3    prior             6          0                 16
32   1839752        3    prior             7          0                 15
33   3225766        3    prior             8          0                 17
34   3160850        3    prior             9          0                 16
35    676467        3    prior            10          3                 16
36    521107        3    prior            11          0                 18
37   1402502        3    prior            12          1                 15
38   2774568        3     test            13          5                 15
39   3343014        4    prior             1          6                 11
40   2030307        4    prior             2          4                 11
41    691089        4    prior             3          4                 15
42     94891        4    prior             4          5                 13
43   2557754        4    prior             5          5                 13
44    329954        4     test             6          3                 12
45   2717275        5    prior             1          3                 12
46   1909121        5    prior             2          0                 16
47   2267326        5    prior             3          3                 18
48    157374        5    prior             4          1                 18
49   2196797        5    train             5          0                 11

    days_since_prior_order
0                      0.0
1                     15.0
2                     21.0
3                     29.0
4                     28.0
5                     19.0
6                     20.0
7                     14.0
8                      0.0
9                     30.0
10                    14.0
11                     0.0
12                    10.0
13                     3.0
14                     8.0
15                     8.0
16                    13.0
17                    14.0
18                    27.0
19                     8.0
20                     6.0
21                    30.0
22                    28.0
23                    30.0
24                    13.0
25                    30.0
26                     0.0
27                     9.0
28                    21.0
29                    20.0
30                    12.0
31                     7.0
32                     7.0
33                     7.0
34                     7.0
35                    17.0
36                    11.0
37                    15.0
38                    11.0
39                     0.0
40                    19.0
41                    21.0
42                    15.0
43                     0.0
44                    30.0
45                     0.0
46                    11.0
47                    10.0
48                    19.0
49                     6.0

order_id                    int64
user_id                     int64
eval_set                   object
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
dtype: object

**Convert data types**

In [14]:
#convert datatypes
#aisle
df_aisles['aisle_id'] = df_aisles['aisle_id'].astype('int64')
df_aisles['aisle'] = df_aisles['aisle'].astype('str')
#df_departments
df_departments['department_id'] = df_departments['department_id'].astype('int64')
df_departments['department'] = df_departments['department'].astype('str')
#df_products
df_products['product_id'] = df_products['product_id'].astype('int64')
df_products['product_name'] = df_products['product_name'].astype('str')
df_products['aisle_id'] = df_products['aisle_id'].astype('int64')
df_products['department_id'] = df_products['department_id'].astype('int64')
#df_order_products
df_order_products['product_id'] = df_order_products['product_id'].astype('int64')
df_order_products['order_id'] = df_order_products['order_id'].astype('int64')
df_order_products['add_to_cart_order'] = df_order_products['add_to_cart_order'].astype('int64')
df_order_products['reordered'] = df_order_products['reordered'].astype('bool')
#df_orders
df_orders['order_id'] = df_orders['order_id'].astype('int64')
df_orders['user_id'] = df_orders['user_id'].astype('int64')
df_orders['eval_set'] = df_orders['eval_set'].astype('str')
df_orders['order_number'] = df_orders['order_number'].astype('int64')
df_orders['order_dow'] = df_orders['order_dow'].astype('int64')
df_orders['order_hour_of_day'] = df_orders['order_hour_of_day'].astype('int64')
df_orders['days_since_prior_order'] = df_orders['days_since_prior_order'].astype('int64')

**Merge DataFrames as needed**

In [15]:
#concat train order and prior orders
order_products_all = df_order_products.sort_values(by=['order_id'])

#merge with rest
order_products_all = pd.merge(left = order_products_all, right = df_products,
                             left_on='product_id', right_on='product_id').sort_values(by=['order_id']).reset_index(drop=True)
order_products_all = pd.merge(left = order_products_all, right = df_aisles,
                             left_on='aisle_id', right_on='aisle_id').sort_values(by=['order_id']).reset_index(drop=True)
order_products_all = pd.merge(left = order_products_all, right = df_departments,
                             left_on='department_id', right_on='department_id').sort_values(by=['order_id']).reset_index(drop=True)
order_products_all = pd.merge(left = order_products_all, right = df_orders,
                             left_on='order_id', right_on='order_id').sort_values(by=['order_id']).reset_index(drop=True)

col_order = ['user_id','order_id','product_id','aisle_id','department_id','add_to_cart_order',
 'reordered','product_name','aisle','department','eval_set','order_number','order_dow','order_hour_of_day',
 'days_since_prior_order']

order_products_all = order_products_all[col_order]

In [16]:
order_products_all.head()

,user_id,order_id,product_id,aisle_id,department_id,add_to_cart_order,reordered,product_name,aisle,department,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,202279,2,43668,123,4,9,False,Classic Blend Cole Slaw,packaged vegetables fruits,produce,prior,3,5,9,8
1,202279,2,33120,86,16,1,True,Organic Egg Whites,eggs,dairy eggs,prior,3,5,9,8
2,202279,2,40141,105,13,7,True,Original Unflavored Gelatine Mix,doughs gelatins bake mixes,pantry,prior,3,5,9,8
3,202279,2,1819,88,13,8,True,All Natural No Stir Creamy Almond Butter,spreads,pantry,prior,3,5,9,8
4,202279,2,17794,83,4,6,True,Carrots,fresh vegetables,produce,prior,3,5,9,8

### c. Basic Descriptive Statistics:
- Calculate summary statistics for numerical features.
- Examine the distribution of categorical features.

**Calculate summary statistics for numerical features.**

In [17]:
order_products_all['user_id'].nunique()

206209

In [18]:
# Summary statistics for numerical features in the order_products_all DataFrame
print("\nSummary Statistics for All Order Products DataFrame:")
order_products_all.describe()

Summary Statistics for All Order Products DataFrame:

,user_id,order_id,product_id,aisle_id,department_id,add_to_cart_order,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,3.243449e+07,3.243449e+07,3.243449e+07,3.243449e+07,3.243449e+07,3.243449e+07,3.243449e+07,3.243449e+07,3.243449e+07,3.243449e+07
mean,1.029372e+05,1.710749e+06,2.557634e+04,7.121430e+01,9.921906e+00,8.351076e+00,1.714205e+01,2.738818e+00,1.342498e+01,1.039264e+01
std,5.946648e+04,9.873007e+05,1.409669e+04,3.820302e+01,6.281156e+00,7.126671e+00,1.753504e+01,2.090049e+00,4.246365e+00,8.917691e+00
min,1.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,5.142100e+04,8.559430e+05,1.353000e+04,3.100000e+01,4.000000e+00,3.000000e+00,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.026110e+05,1.711048e+06,2.525600e+04,8.300000e+01,9.000000e+00,6.000000e+00,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00
75%,1.543910e+05,2.565514e+06,3.793500e+04,1.070000e+02,1.600000e+01,1.100000e+01,2.400000e+01,5.000000e+00,1.600000e+01,1.400000e+01
max,2.062090e+05,3.421083e+06,4.968800e+04,1.340000e+02,2.100000e+01,1.450000e+02,9.900000e+01,6.000000e+00,2.300000e+01,3.000000e+01

In [19]:
order_products_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32434489 entries, 0 to 32434488
Data columns (total 15 columns):
 #   Column                  Dtype
---  ------                  -----
 0   user_id                 int64
 1   order_id                int64
 2   product_id              int64
 3   aisle_id                int64
 4   department_id           int64
 5   add_to_cart_order       int64
 6   reordered               bool
 7   product_name            object
 8   aisle                   object
 9   department              object
 10  eval_set                object
 11  order_number            int64
 12  order_dow               int64
 13  order_hour_of_day       int64
 14  days_since_prior_order  int64
dtypes: bool(1), int64(10), object(4)
memory usage: 3.4+ GB

In [20]:
order_products_all.describe(include='object')

       product_name         aisle department  eval_set
count      32434489      32434489   32434489  32434489
unique        49677           134         21         1
top          Banana  fresh fruits    produce     prior
freq         472565       3642188    9479291  32434489

**Examine the distribution of categorical features.**

In [21]:
# Distribution of categorical features in the order_products_all_merged DataFrame
print("\nDistribution of product_id in All Order Products Merged DataFrame:")
order_products_all['product_name'].value_counts().head()

Distribution of product_id in All Order Products Merged DataFrame:

product_name
Banana                    472565
Bag of Organic Bananas    379450
Organic Strawberries      264683
Organic Baby Spinach      241921
Organic Hass Avocado      213584
Name: count, dtype: int64

In [22]:
print("\nDistribution of aisle_id in All Order Products Merged DataFrame:")
order_products_all['aisle_id'].value_counts().head()

Distribution of aisle_id in All Order Products Merged DataFrame:

aisle_id
24     3642188
83     3418021
123    1765313
120    1452343
21      979763
Name: count, dtype: int64

In [23]:
print("\nDistribution of department_id in All Order Products Merged DataFrame:")
order_products_all['department_id'].value_counts().head()

Distribution of department_id in All Order Products Merged DataFrame:

department_id
4     9479291
16    5414016
19    2887550
7     2690129
1     2236432
Name: count, dtype: int64

## 2. Exploratory Data Analysis (EDA)

### a. Customer Behavior:
- Average number of orders per user.
- Average time between orders for each user.
- Number of orders placed by each customer.
- Customer segments based on purchase frequency.

**Average number of orders per user.**

In [24]:
#Average number of orders per user = Total number of orders / total number of users
no_orders = len(pd.unique(df_orders['order_id']))
no_users = len(pd.unique(df_orders['user_id']))
avg_no = no_orders/no_users
print(f"Average number of orders per use = {avg_no}")

Average number of orders per use = 16.590367054784224

**Average time between orders for each user.**

In [26]:
#Average time between orders for each user
average_days_between_orders = df_orders.groupby('user_id')['days_since_prior_order'].mean()
print(f"Average time between orders for each user = \n{average_days_between_orders}")

Average time between orders for each user =
user_id
1         17.272727
2         15.200000
3         11.076923
4         14.166667
5          9.200000
            ...
206205    12.500000
206206     3.661765
206207    13.470588
206208     7.220000
206209    17.142857
Name: days_since_prior_order, Length: 206209, dtype: float64

**Number of orders placed by each customer.**

In [27]:
#Number of orders placed by each customer
df_customer_groupby = df_orders.groupby('user_id').agg({
    'order_id':'count',
    'days_since_prior_order':'mean'
}).round(2)
print(f"Number of orders placed by each customer = \n{df_customer_groupby}")

Number of orders placed by each customer =
         order_id  days_since_prior_order
user_id
1              11                   17.27
2              15                   15.20
3              13                   11.08
4               6                   14.17
5               5                    9.20
...           ...                     ...
206205          4                   12.50
206206         68                    3.66
206207         17                   13.47
206208         50                    7.22
206209         14                   17.14

[206209 rows x 2 columns]

**Customer segments based on purchase frequency.**

In [28]:
'''
function takes average days between orders and classify customer based on following rules:
# Frequent Buyers: Customers who make purchases regularly (e.g.,weekly or monthly)
# average days between orders FB < 30
# Occasional Buyers: Customers who purchase less frequently (e.g., quarterly).
# average days between orders 30 <= OB < 90
# Rare Buyers: Customers who make very few purchases (e.g., annually).
# average days between orders 90 <= RB 
'''
def customer_segment(avg_days):
    if avg_days < 25 :
        return 'FB'
    elif 25 <= avg_days < 70:
        return 'OB'
    else:
        return 'RB'

#Customer segments based on purchase frequency
order_count = list(df_customer_groupby.order_id)

df_customer_segment= df_customer_groupby.assign(
    segment = [customer_segment(x) for x in order_count]
)
df_customer_segment.reset_index()
df_customer_segment.segment.value_counts()

segment
FB    165998
OB     35798
RB      4413
Name: count, dtype: int64

### b. Product Analysis:
- Identify most popular products by frequency.
- Determine average order size (number of items per order).

**Identify most popular products by frequency.**

In [33]:
#calculate frequency of ordering each product
df_order_product_name = pd.merge(left = df_order_products, right = df_products,
                             left_on='product_id', right_on='product_id').sort_values(by=['order_id']).reset_index(drop=True)
print("\nMost Popular Products by Frequency:")
df_order_product_name.groupby(['product_id','product_name']).agg({'order_id':'count'}).nlargest(10,columns = 'order_id')

Most Popular Products by Frequency:

                                   order_id
product_id product_name
24852      Banana                    472565
13176      Bag of Organic Bananas    379450
21137      Organic Strawberries      264683
21903      Organic Baby Spinach      241921
47209      Organic Hass Avocado      213584
47766      Organic Avocado           176815
47626      Large Lemon               152657
16797      Strawberries              142951
26209      Limes                     140627
27845      Organic Whole Milk        137905

**Determine average order size (number of items per order).**

In [35]:
# Calculate the number of items per order
order_sizes = df_order_products.groupby('order_id').size()

# Calculate the average order size
average_order_size = order_sizes.mean()
print(f"\nAverage Order Size (Number of Items per Order): {average_order_size:.2f}")

Average Order Size (Number of Items per Order): 10.09

### c. Temporal Patterns:
- Analyze orders by day of the week and hour of the day.
- Explore seasonal trends or patterns in purchasing behavior. (will be solved at the end)
- Months with higher order volumes. (will be solved at the end)

**Analyze orders by day of the week and hour of the day.**

In [36]:
orders_by_dow = df_orders['order_dow'].value_counts()
orders_by_hour = df_orders['order_hour_of_day'].value_counts()

orders_by_dow

order_dow
0    600905
1    587478
2    467260
5    453368
6    448761
3    436972
4    426339
Name: count, dtype: int64

In [37]:
orders_by_hour

order_hour_of_day
10    288418
11    284728
15    283639
14    283042
13    277999
12    272841
16    272553
9     257812
17    228795
18    182912
8     178201
19    140569
20    104292
7      91868
21     78109
22     61468
23     40043
6      30529
0      22758
1      12398
5       9569
2       7539
4       5527
3       5474
Name: count, dtype: int64

In [45]:
# Determine if the order was on a weekend or weekday
order_products_all['is_weekend'] = order_products_all['order_dow'].apply(lambda x: x in [0, 6])  # 0 = Sunday, 6 = Saturday
df_orders['is_weekend'] = df_orders['order_dow'].apply(lambda x: x in [0, 6])  # 0 = Sunday, 6 = Saturday

In [39]:
product_order_name = df_orders.join(
    df_order_products.set_index('order_id'), 
    on='order_id', 
    how = 'left'
).join(
    df_products.set_index('product_id'), 
    on='product_id', 
    how = 'left'
)
product_sales_by_day = product_order_name.groupby(['product_id', 'product_name', 'is_weekend'])['order_id'].count().reset_index()
product_sales_by_day

,product_id,product_name,is_weekend,order_id
0,1.0,Chocolate Sandwich Cookies,False,1532
1,1.0,Chocolate Sandwich Cookies,True,320
2,2.0,All-Seasons Salt,False,56
3,2.0,All-Seasons Salt,True,34
4,3.0,Robust Golden Unsweetened Oolong Tea,False,172
...,...,...,...,...
97974,49686.0,Artisan Baguette,True,43
97975,49687.0,Smartblend Healthy Metabolism Dry Cat Food,False,11
97976,49687.0,Smartblend Healthy Metabolism Dry Cat Food,True,2
97977,49688.0,Fresh Foaming Cleanser,False,58
97978,49688.0,Fresh Foaming Cleanser,True,31

In [12]:

popular_products_weekday = product_sales_by_day[product_sales_by_day['is_weekend'] == False].sort_values('order_id', ascending=False)
popular_products_weekday

       product_id                         product_name  is_weekend  order_id
49129     24852.0                               Banana       False    323814
26045     13176.0               Bag of Organic Bananas       False    268435
41806     21137.0                 Organic Strawberries       False    180606
43318     21903.0                 Organic Baby Spinach       False    157547
93282     47209.0                 Organic Hass Avocado       False    145446
...           ...                                  ...         ...       ...
7362       3723.0      Frozen Lemon Simply Yogurt Bars       False         1
40924     20692.0             Fried Rice Seasoning Mix       False         1
24453     12372.0                 Chewy Chocolate Chip       False         1
52276     26441.0              Lf Cottage Cheese 16 Oz       False         1
37785     19107.0  JavaJig Single Serve Coffee Filters       False         1

[49597 rows x 4 columns]

In [40]:
popular_products_weekend = product_sales_by_day[product_sales_by_day['is_weekend'] == True].sort_values('order_id', ascending=False)
popular_products_weekend

,product_id,product_name,is_weekend,order_id
49047,24852.0,Banana,True,160083
26001,13176.0,Bag of Organic Bananas,True,120740
41736,21137.0,Organic Strawberries,True,90554
43246,21903.0,Organic Baby Spinach,True,90038
93086,47209.0,Organic Hass Avocado,True,72457
...,...,...,...,...
40549,20537.0,Lemonade Juice Not From Concentrate,True,1
40604,20565.0,Muenster Natural Cheese,True,1
40600,20563.0,1F Organic Bananas Organic Purees Fruit,True,1
40507,20515.0,Long Lasting Highly Absorbent Utility Sponges,True,1
97934,49666.0,Ginger Snaps Snacking Cookies,True,1

### d. Basket Analysis:
- Identify most frequently co-purchased items.
- Products often bought together on weekends vs. weekdays.

**Identify most frequently co-purchased items.**

In [46]:
chunk = order_products_all.head(100000)

In [47]:
# Create a new DataFrame with all possible pairs within each order
merged = pd.merge(chunk, chunk, on='order_id')

# Filter out self-pairs and sort product pairs
merged = merged[merged['product_id_x'] != merged['product_id_y']]
merged['product_pair'] = merged.apply(lambda row: tuple(sorted((row['product_id_x'], row['product_id_y']))), axis=1)

In [48]:
# Group by product pairs and count occurrences
pair_counts = merged.groupby('product_pair').size().reset_index(name='frequency')

# Sort by frequency and return top 10
copurchased_pairs = pair_counts.sort_values('frequency', ascending=False)

copurchased_pairs.head(10)

          product_pair  frequency
251566  (13176, 47209)        378
371181  (21137, 24852)        372
248933  (13176, 21137)        340
426998  (24852, 47766)        316
249013  (13176, 21903)        314
384258  (21903, 24852)        296
306252  (16797, 24852)        266
249628  (13176, 27966)        262
370971  (21137, 21903)        250
372853  (21137, 47209)        232

**Products often bought together on weekends vs. weekdays.**

In [49]:
merged_weekend = merged[merged['is_weekend_x'] & merged['is_weekend_y']]
pair_counts_weekend = merged_weekend.groupby('product_pair').size().reset_index(name='frequency')

# Sort by frequency and return top 10
copurchased_pairs_weekend = pair_counts_weekend.sort_values('frequency', ascending=False)

copurchased_pairs_weekend.head()

          product_pair  frequency
94871   (13176, 47209)        148
138992  (21137, 24852)        136
144041  (21903, 24852)        122
93600   (13176, 21903)        120
93565   (13176, 21137)        112

In [50]:
merged_weekend = merged[merged['is_weekend_x'] & merged['is_weekend_y']]
pair_counts_weekend = merged_weekend.groupby('product_pair').size().reset_index(name='frequency')

# Sort by frequency and return top 10
copurchased_pairs_weekend = pair_counts_weekend.sort_values('frequency', ascending=False)

copurchased_pairs_weekend.head()

          product_pair  frequency
94871   (13176, 47209)        148
138992  (21137, 24852)        136
144041  (21903, 24852)        122
93600   (13176, 21903)        120
93565   (13176, 21137)        112

## 3. Business Questions and Analysis

### a. Popular Products:
- Analyze sales distribution of top-selling products.
- Identify top 5 products commonly added to the cart first.
- Top 10 product pairs frequently purchased together.

**Analyze sales distribution of top-selling products.**

In [56]:
df_order_product_name.groupby(['product_id','product_name']).agg({
'order_id':'count'
}).nlargest(10,columns = 'order_id')

                                   order_id
product_id product_name
24852      Banana                    472565
13176      Bag of Organic Bananas    379450
21137      Organic Strawberries      264683
21903      Organic Baby Spinach      241921
47209      Organic Hass Avocado      213584
47766      Organic Avocado           176815
47626      Large Lemon               152657
16797      Strawberries              142951
26209      Limes                     140627
27845      Organic Whole Milk        137905

**Identify top 5 products commonly added to the cart first.**

In [57]:
df_order_product_name[df_order_products.add_to_cart_order == 1].groupby(['product_id','product_name']).agg({
'order_id':'count'
}).nlargest(5,columns = 'order_id')

                                   order_id
product_id product_name
24852      Banana                     49983
13176      Bag of Organic Bananas     44579
21137      Organic Strawberries       26622
21903      Organic Baby Spinach       24655
47209      Organic Hass Avocado       20107

**Top 10 product pairs frequently purchased together.**

In [59]:
copurchased_pairs.head(10)

          product_pair  frequency
251566  (13176, 47209)        378
371181  (21137, 24852)        372
248933  (13176, 21137)        340
426998  (24852, 47766)        316
249013  (13176, 21903)        314
384258  (21903, 24852)        296
306252  (16797, 24852)        266
249628  (13176, 27966)        262
370971  (21137, 21903)        250
372853  (21137, 47209)        232

### b. Reorder Behavior:
- Analyze the reordered column to understand repeat purchase behavior.
- Products reordered the most.
- Reorder behavior based on day of the week and days since prior order.
- How the number of items in the cart impacts the likelihood of reordering.

**Analyze the reordered column to understand repeat purchase behavior.**

**Products reordered the most.**

In [60]:
# Count reordered products
reordered_products = order_products_all[order_products_all['reordered'] == 1]['product_id'].nunique()
total_products = order_products_all['product_id'].nunique()

# Calculate reorder rate
reorder_rate = reordered_products / total_products

print("Reorder rate:", reorder_rate)

# Identify top reordered products
top_reordered_products = order_products_all[order_products_all['reordered'] == 1].groupby('product_id').size().reset_index(name='reorder_count').sort_values('reorder_count', ascending=False)

top_reordered_products.head(5)

Reorder rate: 0.9119914648630151

       product_id  reorder_count
22680       24852         398609
11997       13176         315913
19282       21137         205845
19973       21903         186884
43048       47209         170131

**Reorder behavior based on day of the week and days since prior order.**

In [61]:
# Filter for reordered products
reordered_data = order_products_all[order_products_all['reordered'] == 1]

# Calculate reorder rate by day of week
reordered_by_day = reordered_data.groupby(reordered_data['order_dow'])['product_id'].nunique() / reordered_data['product_id'].nunique()

# Calculate reorder rate by days since prior order
reordered_by_days_since_prior_order = reordered_data.groupby('days_since_prior_order')['product_id'].nunique() / reordered_data['product_id'].nunique()

**How the number of items in the cart impacts the likelihood of reordering.**

In [62]:
# Group by order_id and count items in the cart
order_data = order_products_all.groupby('order_id').size().reset_index(name='cart_size')

# Merge with original DataFrame
merged_data = pd.merge(order_products_all, order_data, on='order_id')

# Calculate reorder rate by cart size
reordered_by_cart_size = merged_data[merged_data['reordered'] == 1].groupby('cart_size')['product_id'].nunique() / merged_data['product_id'].nunique()

In [63]:
reordered_by_cart_size.sort_values(ascending=False)

cart_size
9      0.583972
10     0.583671
8      0.580289
11     0.575075
7      0.574310
         ...
145    0.001610
90     0.001469
105    0.001027
114    0.000845
127    0.000081
Name: product_id, Length: 113, dtype: float64

### d. Department and Aisle Analysis:
- Best-selling department and aisle breakdown.
- What is the “produce” department? Break it down by aisle.
- Differences in purchasing behavior based on different departments or aisles.

**Best-selling department and aisle breakdown.**

In [64]:
Best_selling_products = list(df_order_products.groupby('product_id').agg({
'order_id':'count'
}).nlargest(20,columns = 'order_id').index)
df_products[df_products.product_id.isin(Best_selling_products)].join(
df_departments.set_index('department_id'),
on='department_id',
how = 'left'
).join(
df_aisles.set_index('aisle_id'),
on='aisle_id',
how = 'left'
)

,product_id,product_name,aisle_id,department_id,department,aisle
5875,5876,Organic Lemon,24,4,produce,fresh fruits
8276,8277,Apple Honeycrisp Organic,24,4,produce,fresh fruits
13175,13176,Bag of Organic Bananas,24,4,produce,fresh fruits
16796,16797,Strawberries,24,4,produce,fresh fruits
21136,21137,Organic Strawberries,24,4,produce,fresh fruits
21902,21903,Organic Baby Spinach,123,4,produce,packaged vegetables fruits
22934,22935,Organic Yellow Onion,83,4,produce,fresh vegetables
24851,24852,Banana,24,4,produce,fresh fruits
24963,24964,Organic Garlic,83,4,produce,fresh vegetables
26208,26209,Limes,24,4,produce,fresh fruits
27844,27845,Organic Whole Milk,84,16,dairy eggs,milk
27965,27966,Organic Raspberries,123,4,produce,packaged vegetables fruits
28203,28204,Organic Fuji Apple,24,4,produce,fresh fruits
39274,39275,Organic Blueberries,123,4,produce,packaged vegetables fruits
40705,40706,Organic Grape Tomatoes,123,4,produce,packaged vegetables fruits
45006,45007,Organic Zucchini,83,4,produce,fresh vegetables
47208,47209,Organic Hass Avocado,24,4,produce,fresh fruits
47625,47626,Large Lemon,24,4,produce,fresh fruits
47765,47766,Organic Avocado,24,4,produce,fresh fruits
49682,49683,Cucumber Kirby,83,4,produce,fresh vegetables

**What is the “produce” department? Break it down by aisle.**

In [65]:
temp = df_products[df_products.department_id == 4].join(
df_departments.set_index('department_id'),
on='department_id',
how = 'left'
).join(
df_aisles.set_index('aisle_id'),
on='aisle_id',
how = 'left'
)
pd.unique(temp['aisle'])

array(['packaged vegetables fruits', 'fresh vegetables', 'fresh fruits',
       'fresh herbs', 'packaged produce'], dtype=object)

**Differences in purchasing behavior based on different departments or aisles.**

In [66]:
# Calculate average order size by department and aisle
average_order_size = order_products_all.groupby(['department', 'aisle']).size().reset_index(name='order_size')
average_order_size

    department                       aisle  order_size
0      alcohol               beers coolers       48657
1      alcohol                   red wines       35181
2      alcohol  specialty wines champagnes       11198
3      alcohol                     spirits       28102
4      alcohol                 white wines       30558
..         ...                         ...         ...
129     snacks          ice cream toppings       11202
130     snacks                    mint gum       22664
131     snacks      nuts seeds dried fruit      306487
132     snacks               popcorn jerky      163524
133     snacks         trail mix snack mix       35590

[134 rows x 3 columns]

In [67]:
# Calculate reorder rate by department and aisle
reordered_data = order_products_all[order_products_all['reordered'] == 1]
reordered_data

,user_id,order_id,product_id,aisle_id,department_id,add_to_cart_order,reordered,product_name,aisle,department,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,is_weekend
1,202279,2,33120,86,16,1,True,Organic Egg Whites,eggs,dairy eggs,prior,3,5,9,8,False
2,202279,2,40141,105,13,7,True,Original Unflavored Gelatine Mix,doughs gelatins bake mixes,pantry,prior,3,5,9,8,False
3,202279,2,1819,88,13,8,True,All Natural No Stir Creamy Almond Butter,spreads,pantry,prior,3,5,9,8,False
4,202279,2,17794,83,4,6,True,Carrots,fresh vegetables,produce,prior,3,5,9,8,False
6,202279,2,28985,83,4,2,True,Michigan Organic Kale,fresh vegetables,produce,prior,3,5,9,8,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32434477,175185,3421082,43352,32,4,4,True,Raspberries,packaged produce,produce,prior,23,2,18,4,False
32434484,25247,3421083,5020,3,19,10,True,Organic Sweet & Salty Peanut Pretzel Granola ...,energy granola bars,snacks,prior,24,2,6,21,False
32434485,25247,3421083,18176,92,18,4,True,Organic Strawberry Yogurt & Fruit Snack,baby food formula,babies,prior,24,2,6,21,False
32434486,25247,3421083,39678,74,17,6,True,Free & Clear Natural Dishwasher Detergent,dish detergents,household,prior,24,2,6,21,False
32434487,25247,3421083,24852,24,4,9,True,Banana,fresh fruits,produce,prior,24,2,6,21,False

In [68]:
reorder_rate = reordered_data.groupby(['department', 'aisle']).size() / order_products_all.groupby(['department', 'aisle']).size()
reorder_rate

department  aisle
alcohol     beers coolers                 0.565304
            red wines                     0.548734
            specialty wines champagnes    0.486337
            spirits                       0.572344
            white wines                   0.630081
                                            ...
snacks      ice cream toppings            0.266917
            mint gum                      0.558904
            nuts seeds dried fruit        0.519170
            popcorn jerky                 0.591986
            trail mix snack mix           0.620230
Length: 134, dtype: float64

In [69]:
# Analyze customer demographics by department and aisle
customer_demographics = order_products_all.groupby(['department', 'aisle']).agg({'user_id': 'nunique'})
customer_demographics

                                       user_id
department aisle
alcohol    beers coolers                  8061
           red wines                      7073
           specialty wines champagnes     3764
           spirits                        5695
           white wines                    6364
...                                        ...
snacks     ice cream toppings             6693
           mint gum                       6721
           nuts seeds dried fruit        76177
           popcorn jerky                 44854
           trail mix snack mix           11718

[134 rows x 1 columns]

## Date-based Analytics

In [70]:
orders_chunk = df_orders.head(1000)

In [75]:
# Create a starting date for simulation
start_date = pd.to_datetime('2023-08-20')  # Choose a reference date

# Sort orders by user_id and order_number
orders_sorted = orders_chunk.sort_values(by=['user_id', 'order_number'])

In [76]:
# Generate simulated dates based on days_since_prior_order
from datetime import timedelta
for user_id, group in orders_sorted.groupby('user_id'):
    prev_date = start_date
    for index, row in group.iterrows():
        if row['order_number'] == 1:
            prev_date = start_date+ timedelta(days=row['order_dow'])
        else:
            prev_date = prev_date + timedelta(days=row['days_since_prior_order'])
            
        orders_sorted.loc[((df_orders['order_id'] == row['order_id']) & (df_orders['user_id'] == row['user_id'])),\
        'date_of_order'] = pd.to_datetime(prev_date)

In [77]:
orders_sorted

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,is_weekend,date_of_order
0,2539329,1,prior,1,2,8,0,False,2023-08-22
1,2398795,1,prior,2,3,7,15,False,2023-09-06
2,473747,1,prior,3,3,12,21,False,2023-09-27
3,2254736,1,prior,4,4,7,29,False,2023-10-26
4,431534,1,prior,5,4,15,28,False,2023-11-23
...,...,...,...,...,...,...,...,...,...
995,2302602,64,prior,7,5,20,9,False,2023-10-20
996,3215917,64,prior,8,6,17,15,True,2023-11-04
997,2754807,64,prior,9,6,15,7,True,2023-11-11
998,3129760,64,prior,10,1,10,9,False,2023-11-20
999,2639013,64,train,11,0,13,27,True,2023-12-17

**Explore seasonal trends or patterns in purchasing behavior.**

In [78]:
# Calculate quarterly sales
sales_by_quarter = orders_sorted.groupby(pd.Grouper(key='date_of_order', freq='QE'))['order_id'].count()
sales_by_quarter

date_of_order
2023-09-30    248
2023-12-31    338
2024-03-31    225
2024-06-30    138
2024-09-30     51
Freq: QE-DEC, Name: order_id, dtype: int64

**Months with higher order volumes.**

In [79]:
# Add a month column for aggregation
orders_sorted['month'] = orders_sorted['date_of_order'].dt.to_period('M')

# Calculate monthly order volumes
monthly_order_volumes = orders_sorted.groupby('month').size()

print("\nMonthly Order Volumes:")
print(monthly_order_volumes)

Monthly Order Volumes:
month
2023-08     95
2023-09    153
2023-10    130
2023-11    121
2023-12     87
2024-01     80
2024-02     67
2024-03     78
2024-04     57
2024-05     46
2024-06     35
2024-07     31
2024-08     20
Freq: M, dtype: int64

In [80]:
orders_sorted['date_of_order'].describe()

count                          1000
mean     2023-12-24 12:24:28.800000
min             2023-08-20 00:00:00
25%             2023-10-01 00:00:00
50%             2023-12-01 00:00:00
75%             2024-03-07 06:00:00
max             2024-08-21 00:00:00
Name: date_of_order, dtype: object

**Identify customers who haven’t placed an order in the last 30 days.**

In [81]:
import datetime

# Calculate the current date
current_date = datetime.datetime.now()

# Identify customers who have placed orders in the last 30 days
recent_customers = orders_sorted[orders_sorted['date_of_order'] >= current_date - pd.Timedelta(days=30)]['user_id'].unique()

# Find all customers
all_customers = orders_sorted['user_id'].unique()

# Identify inactive customers
inactive_customers = set(all_customers) - set(recent_customers)

# Create DataFrame for inactive customers
inactive_customers_df = pd.DataFrame(list(inactive_customers), columns=['user_id'])

inactive_customers_df

    user_id
0         1
1         2
2         3
3         4
4         5
..      ...
59       60
60       61
61       62
62       63
63       64

[64 rows x 1 columns]

**Percentage of customers who have churned in the past quarter.**

In [83]:
# This example assumes a quarter is 3 months
quarter_start_date = current_date - pd.DateOffset(months=3)

# Identify customers who have placed orders in the past quarter
recent_customers = orders_sorted[
    (orders_sorted['date_of_order'] >= quarter_start_date) & 
    (orders_sorted['date_of_order'] <= current_date)
]['user_id'].unique()

# Find all customers
all_customers = orders_sorted['user_id'].unique()

# Identify churned customers
churned_customers = set(all_customers) - set(recent_customers)

# Calculate the percentage of churned customers
churned_customers_count = len(churned_customers)
total_customers_count = len(all_customers)
churn_rate_percentage = (churned_customers_count / total_customers_count) * 100

churn_rate_percentage

90.625